{% set name = "vl-convert-python" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz  # [not arm64 and not aarch64]
  sha256: de1462151dfbba7b2a17881dac1d2269662012c252f1e9d1537a4daed5e36067                              # [not arm64 and not aarch64]

  url: https://files.pythonhosted.org/packages/7d/d8/200a2c04e1f85ac6428b62b126185a0c28beeb51b4c634c28ee911a82e94/vl_convert_python-{{ version }}-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl  # [linux and aarch64]
  sha256: aad714796a7bc3577550690378c088b686d28b4d9e45f92b71f78c5d59025ebb  # [linux and aarch64]

  url: https://files.pythonhosted.org/packages/6b/35/78e6e810aa5c4698a83c846f99eeb0d0a14e2fdab32e9e18922364f6f968/vl_convert_python-{{ version }}-cp37-abi3-macosx_11_0_arm64.whl  # [osx and arm64]
  sha256: db5e2e99f1cad6e585ac163a96e622b0a8a790ca2393c8633efe48494419b50a  # [osx and arm64]

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv       # [not arm64 and not aarch64]
  script: cp vl_convert_python*/license_files/LICENSE . && {{ PYTHON }} -m pip install *.whl -vv   # [arm64 or aarch64]
  binary_relocation: False                # [arm64 or aarch64]
  detect_binary_files_with_prefix: False  # [arm64 or aarch64]
  ignore_prefix_files: True               # [arm64 or aarch64]
  skip: true   # [aarch64 and python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make                       # [not win]
    - cmake
    - rust >=1.64.0
    - python                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - protobuf
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE                                     # [arm64 or aarch64]
    - vl-convert-python/LICENSE                   # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_font.md        # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_javascript.md  # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_rust.yaml      # [not arm64 and not aarch64]

extra:
  recipe-maintainers:
    - jonmmease
