{% set name = "vl-convert-python" %}
{% set version = "1.8.0" %}
{% set whl = "whl" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz  # [not arm64 and not aarch64]
  sha256: ceca613ca5551c55270a15ca48d0f3a7de1e949e0f127310e9b0f6570ea3fbbb  # [not arm64 and not aarch64]
  patches:   # [not arm64 and not aarch64]
    - 01-fix-libffi-msvc.patch  # [not arm64 and not aarch64]

  url: https://files.pythonhosted.org/packages/15/08/06945bff9655c5b0520a8d1b2550cd8007e106ebec45a33840035420e0d2/vl_convert_python-{{ version }}.tar.gz  # [linux and aarch64]
  sha256: ceca613ca5551c55270a15ca48d0f3a7de1e949e0f127310e9b0f6570ea3fbbb  # [linux and aarch64]

  url: https://files.pythonhosted.org/packages/15/08/06945bff9655c5b0520a8d1b2550cd8007e106ebec45a33840035420e0d2/vl_convert_python-{{ version }}.tar.gz  # [osx and arm64]
  sha256: ceca613ca5551c55270a15ca48d0f3a7de1e949e0f127310e9b0f6570ea3fbbb  # [osx and arm64]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv  # [not arm64 and not aarch64]
  script: cp vl_convert_python*/licenses/LICENSE . && {{ PYTHON }} -m pip install *.whl -vv  # [arm64 or aarch64]
  binary_relocation: false  # [arm64 or aarch64]
  detect_binary_files_with_prefix: false  # [arm64 or aarch64]
  ignore_prefix_files: true  # [arm64 or aarch64]
  skip: true  # [aarch64 and python_impl == 'pypy']
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}
    - make                       # [not win]
    - cmake
    - rust >=1.64.0
    - protobuf
    - libffi  # [win]
  host:
    - python
    - pip
    - maturin
  run:
    - python

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE                                     # [arm64 or aarch64]
    - vl-convert-python/LICENSE                   # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_font.md        # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_javascript.md  # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_rust.yaml      # [not arm64 and not aarch64]

extra:
  recipe-maintainers:
    - jonmmease
