{% set name = "vl-convert-python" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz  # [not arm64]
  sha256: a2279a6a4b8e5aefa713ecc1f999d684656a6e37fca1c25114c66def3e867f14                              # [not arm64]
  url: https://files.pythonhosted.org/packages/f7/1c/7ceb521a481acd6f5f420a03b72b2a3f61adf5ac114402bb3afca23d2666/vl_convert_python-{{ version }}-cp37-abi3-macosx_11_0_arm64.whl  # [arm64]
  sha256: 02d6af605b4c2265066a28ac965a7498a6059a653b67274ad655beb5e4ddc393  # [arm64]

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv       # [not arm64]
  script: cp vl_convert_python*/license_files/LICENSE . && {{ PYTHON }} -m pip install *.whl -vv   # [arm64]
  binary_relocation: False                # [arm64]
  detect_binary_files_with_prefix: False  # [arm64]
  ignore_prefix_files: True               # [arm64]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make                       # [not win]
    - rust >=1.64.0
    - python                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - thirdparty_font.md        # [not arm64]
    - thirdparty_javascript.md  # [not arm64]
    - thirdparty_rust.yaml      # [not arm64]

extra:
  recipe-maintainers:
    - jonmmease
