{% set name = "vl-convert-python" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz  # [not arm64]
  sha256: 3e776a8c7d7297b078830ff56a46754aaf5c139a78b4aaa5bbc13bc6f6a87c31                              # [not arm64]
  url: https://files.pythonhosted.org/packages/9d/97/ac5d7b156b52cdf9277525bb8cc7770b630bb5eed38165e41254f8af0199/vl_convert_python-{{ version }}-cp37-abi3-macosx_11_0_arm64.whl  # [arm64]
  sha256: 9122ebca0a8fe54492019b395acca618595fc7b2f1d09a0e77cd0fbcd471b1a8  # [arm64]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv       # [not arm64]
  script: cp vl_convert_python*/license_files/LICENSE . && {{ PYTHON }} -m pip install *.whl -vv   # [arm64]
  binary_relocation: False                # [arm64]
  detect_binary_files_with_prefix: False  # [arm64]
  ignore_prefix_files: True               # [arm64]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make                       # [not win]
    - cmake
    - rust >=1.64.0
    - python                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - protobuf
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE                                     # [arm64]
    - vl-convert-python/LICENSE                   # [not arm64]
    - vl-convert-python/thirdparty_font.md        # [not arm64]
    - vl-convert-python/thirdparty_javascript.md  # [not arm64]
    - vl-convert-python/thirdparty_rust.yaml      # [not arm64]

extra:
  recipe-maintainers:
    - jonmmease
