{% set name = "vl-convert-python" %}
{% set version = "1.6.0" %}
{% set whl = "whl" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz  # [not arm64 and not aarch64]
  sha256: f7539c5558026d41d870df3ea92546ef87956c7b62ca99426906e941115bfd41                              # [not arm64 and not aarch64]
  patches:  # [not arm64 and not aarch64]
    - 01-fix-libffi-msvc.patch  # [not arm64 and not aarch64]

  url: https://files.pythonhosted.org/packages/03/75/d4d697963db4467fba17476423874d1e581359966e7a59ab6a3d69807c0b/vl_convert_python-{{ version }}-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.{{ whl }}  # [linux and aarch64]
  sha256: 1d016d8d0be7a4ebb9dea447e0fe4373fb2998828ca05ae1b50c01d896edcece  # [linux and aarch64]

  url: https://files.pythonhosted.org/packages/90/16/405caeb736f870439e153319346b9544f3364efa30c8cd8f07efd8f44600/vl_convert_python-{{ version }}-cp37-abi3-macosx_11_0_arm64.{{ whl }}  # [osx and arm64]
  sha256: 1c2ca0c2800925a1c6cf0cca4c79291205ceebabf1e9a40f90dd8bcead1af6eb  # [osx and arm64]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv       # [not arm64 and not aarch64]
  script: cp vl_convert_python*/license_files/LICENSE . && {{ PYTHON }} -m pip install *.whl -vv   # [arm64 or aarch64]
  binary_relocation: False                # [arm64 or aarch64]
  detect_binary_files_with_prefix: False  # [arm64 or aarch64]
  ignore_prefix_files: True               # [arm64 or aarch64]
  skip: true   # [aarch64 and python_impl == 'pypy']
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('c') }}
    - make                       # [not win]
    - cmake
    - rust >=1.64.0
    - protobuf
    - libffi  # [win]
  host:
    - python
    - pip
    - maturin
  run:
    - python

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE                                     # [arm64 or aarch64]
    - vl-convert-python/LICENSE                   # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_font.md        # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_javascript.md  # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_rust.yaml      # [not arm64 and not aarch64]

extra:
  recipe-maintainers:
    - jonmmease
