{% set name = "vl-convert-python" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz  # [not arm64 and not aarch64]
  sha256: 264d6f2338c7d3474e60c6907cca016b880b0c1c9be302bb84abc6690188a7e9                              # [not arm64 and not aarch64]
  url: https://files.pythonhosted.org/packages/1b/83/995dc804b1e647800e64bf0ed7b813f4e2b61b4edb16d0a335638c332fb6/vl_convert_python-{{ version }}-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl  # [linux and aarch64]
  sha256: 6c1f61306ecd5a8040c0badf32e733a46f0553de74a6f341a8ff392a95b4daac  # [linux and aarch64]
  url: https://files.pythonhosted.org/packages/2d/7b/cb16ad3e2f79a38187fc484e704698ffb491e9fcd639c6a907cc61a62d2b/vl_convert_python-{{ version }}-cp37-abi3-macosx_11_0_arm64.whl  # [osx and arm64]
  sha256: 6c86472dd1149010f66116b2a98943c8e7fa48a89667428c187a2ea52015f3c8  # [osx and arm64]

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv       # [not arm64 and not aarch64]
  script: cp vl_convert_python*/license_files/LICENSE . && {{ PYTHON }} -m pip install *.whl -vv   # [arm64 or aarch64]
  binary_relocation: False                # [arm64 or aarch64]
  detect_binary_files_with_prefix: False  # [arm64 or aarch64]
  ignore_prefix_files: True               # [arm64 or aarch64]
  skip: true   # [aarch64 and python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make                       # [not win]
    - cmake
    - rust >=1.64.0
    - python                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - protobuf
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE                                     # [arm64 or aarch64]
    - vl-convert-python/LICENSE                   # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_font.md        # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_javascript.md  # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_rust.yaml      # [not arm64 and not aarch64]

extra:
  recipe-maintainers:
    - jonmmease
