{% set name = "vl-convert-python" %}
{% set version = "1.5.1" %}
{% set whl = "whl" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz  # [not arm64 and not aarch64]
  sha256: 014d47361d5f21bbd2f3e3c58455609b9c4ace65f7ccdd881243274f3f91f457                              # [not arm64 and not aarch64]
  patches:  # [not arm64 and not aarch64]
    - 01-fix-libffi-msvc.patch  # [not arm64 and not aarch64]

  url: https://files.pythonhosted.org/packages/00/70/c09e6ea49e963fdf68f28fe45ea2d603cbcaf5716c29bace894b30e3c8b0/vl_convert_python-{{ version }}-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.{{ whl }}  # [linux and aarch64]
  sha256: d72fbcf9a70d3543654532d773cabc87e07eee60cbbd9f235942f151840a539e  # [linux and aarch64]

  url: https://files.pythonhosted.org/packages/e4/ae/6ef3e62834e289f974a6256c1ede3a610297c1ef6565b3ca67cbd1fd7d86/vl_convert_python-{{ version }}-cp37-abi3-macosx_11_0_arm64.{{ whl }}  # [osx and arm64]
  sha256: fe7038cb924f554ca17b66d56e253921a9b6b44fc6b42c2868ac42cd9c3b5459  # [osx and arm64]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv       # [not arm64 and not aarch64]
  script: cp vl_convert_python*/license_files/LICENSE . && {{ PYTHON }} -m pip install *.whl -vv   # [arm64 or aarch64]
  binary_relocation: False                # [arm64 or aarch64]
  detect_binary_files_with_prefix: False  # [arm64 or aarch64]
  ignore_prefix_files: True               # [arm64 or aarch64]
  skip: true   # [aarch64 and python_impl == 'pypy']
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('c') }}
    - make                       # [not win]
    - cmake
    - rust >=1.64.0
    - protobuf
    - libffi  # [win]
  host:
    - python
    - pip
    - maturin
  run:
    - python

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE                                     # [arm64 or aarch64]
    - vl-convert-python/LICENSE                   # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_font.md        # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_javascript.md  # [not arm64 and not aarch64]
    - vl-convert-python/thirdparty_rust.yaml      # [not arm64 and not aarch64]

extra:
  recipe-maintainers:
    - jonmmease
