{% set name = "vl-convert-python" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz  # [not arm64]
  sha256: d70a608257dd6b5b782d96cccebfe7289992e522e47a8bebb7d928253ca8b396                              # [not arm64]
  url: https://files.pythonhosted.org/packages/01/25/60b8c323f7184cb5537665e405217853cfd4f9501db0c7aada1ae564ef5e/vl_convert_python-{{ version }}-cp37-abi3-macosx_11_0_arm64.whl  # [arm64]
  sha256: fdee863e96ebae784a6497a5a8976124febfe4a93d766fa41db973f85d369003  # [arm64]

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv       # [not arm64]
  script: cp vl_convert_python*/license_files/LICENSE . && {{ PYTHON }} -m pip install *.whl -vv   # [arm64]
  binary_relocation: False                # [arm64]
  detect_binary_files_with_prefix: False  # [arm64]
  ignore_prefix_files: True               # [arm64]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make                       # [not win]
    - cmake
    - rust >=1.64.0
    - python                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - thirdparty_font.md        # [not arm64]
    - thirdparty_javascript.md  # [not arm64]
    - thirdparty_rust.yaml      # [not arm64]

extra:
  recipe-maintainers:
    - jonmmease
