{% set name = "vl-convert-python" %}
{% set version = "2.0.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz
  sha256: 29bb5ed68e41e4e49b14691bfa5d309e3b29e07ce23ecb75fd1a252b7c85cf73

build:
  number: 0
  python_version_independent: true  # [is_abi3]
  skip: true  # [is_abi3 and not is_python_min]
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}
    - make                       # [not win]
    - cmake
    - rust >=1.90.0
    - protobuf
    - libclang               # [linux]
    - llvmdev                # [linux]
    - nasm                   # [win]
  host:
    - python-abi3            # [is_abi3]
    - python
    - pip
    - maturin
    - sqlite
    - pkg-config
  run:
    - python

test:
  imports:
    - vl_convert
  commands:
    - pip check
    - abi3audit $SP_DIR/vl_convert/vl_convert.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}  # [unix and is_abi3]
    - abi3audit %SP_DIR%/vl_convert/vl_convert.pyd -s -v --assume-minimum-abi3 {{ python_min }}  # [win and is_abi3]
  requires:
    - pip
    - abi3audit              # [is_abi3]

about:
  home: https://github.com/vega/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - vl-convert-python/LICENSE
    - vl-convert-python/thirdparty_font.md
    - vl-convert-python/thirdparty_javascript.md
    - vl-convert-python/thirdparty_rust.yaml

extra:
  recipe-maintainers:
    - jonmmease
