{% set name = "vl-convert-python" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz  # [not arm64]
  sha256: 8cde0690434b6ece26df0206bb7dfc76c9b3cea73d7085a1ced59ccb3526a1c6                              # [not arm64]
  url: https://files.pythonhosted.org/packages/74/ff/3033b8898ba80cf464739bc3cd0780ebe38cf69949d0388dd3ecc004e61f/vl_convert_python-{{ version }}-cp37-abi3-macosx_11_0_arm64.whl  # [arm64]
  sha256: 15163ba71e528f1a1a7f46918098865ef620e8a5134b7d00fc14ac8e79b5fea1  # [arm64]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv       # [not arm64]
  script: cp vl_convert_python*/license_files/LICENSE . && {{ PYTHON }} -m pip install *.whl -vv   # [arm64]
  binary_relocation: False                # [arm64]
  detect_binary_files_with_prefix: False  # [arm64]
  ignore_prefix_files: True               # [arm64]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make                       # [not win]
    - cmake
    - rust >=1.64.0
    - python                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - protobuf
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE                                     # [arm64]
    - vl-convert-python/LICENSE                   # [not arm64]
    - vl-convert-python/thirdparty_font.md        # [not arm64]
    - vl-convert-python/thirdparty_javascript.md  # [not arm64]
    - vl-convert-python/thirdparty_rust.yaml      # [not arm64]

extra:
  recipe-maintainers:
    - jonmmease
