{% set name = "vl-convert-python" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz
  sha256: f1c7cb9b9071712519c19b26e0815709b782d97ae3cb6953e240a91b708a01e1

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make                       # [not win]
    - {{ compiler('rust') }}
  host:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pip
    - maturin
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.11") }}  # [osx and x86_64]

test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - thirdparty_font.md
    - thirdparty_javascript.md
    - thirdparty_rust.yaml

extra:
  recipe-maintainers:
    - jonmmease
